// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;
using namespace arma;
using namespace std;

// readfile
void readfile(string fname, int nsamp, vector<int> RandomLags, int num_threads);
RcppExport SEXP _FastSparseGRM_readfile(SEXP fnameSEXP, SEXP nsampSEXP, SEXP RandomLagsSEXP, SEXP num_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< string >::type fname(fnameSEXP);
    Rcpp::traits::input_parameter< int >::type nsamp(nsampSEXP);
    Rcpp::traits::input_parameter< vector<int> >::type RandomLags(RandomLagsSEXP);
    Rcpp::traits::input_parameter< int >::type num_threads(num_threadsSEXP);
    readfile(fname, nsamp, RandomLags, num_threads);
    return R_NilValue;
END_RCPP
}
// setmeans
void setmeans(vector<int> idmean, int noscale);
RcppExport SEXP _FastSparseGRM_setmeans(SEXP idmeanSEXP, SEXP noscaleSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vector<int> >::type idmean(idmeanSEXP);
    Rcpp::traits::input_parameter< int >::type noscale(noscaleSEXP);
    setmeans(idmean, noscale);
    return R_NilValue;
END_RCPP
}
// deletedata
void deletedata();
RcppExport SEXP _FastSparseGRM_deletedata() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    deletedata();
    return R_NilValue;
END_RCPP
}
// deletetranspose
void deletetranspose();
RcppExport SEXP _FastSparseGRM_deletetranspose() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    deletetranspose();
    return R_NilValue;
END_RCPP
}
// postmultiply
arma::mat postmultiply(NumericMatrix u, vector<int> idmult);
RcppExport SEXP _FastSparseGRM_postmultiply(SEXP uSEXP, SEXP idmultSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< vector<int> >::type idmult(idmultSEXP);
    rcpp_result_gen = Rcpp::wrap(postmultiply(u, idmult));
    return rcpp_result_gen;
END_RCPP
}
// premultiply
arma::mat premultiply(NumericMatrix u, vector<int> idmult);
RcppExport SEXP _FastSparseGRM_premultiply(SEXP uSEXP, SEXP idmultSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type u(uSEXP);
    Rcpp::traits::input_parameter< vector<int> >::type idmult(idmultSEXP);
    rcpp_result_gen = Rcpp::wrap(premultiply(u, idmult));
    return rcpp_result_gen;
END_RCPP
}
// calcRel
arma::mat calcRel(int beginInd, int endInd, mat beta, mat score, vector<int> id1, vector<int> id2);
RcppExport SEXP _FastSparseGRM_calcRel(SEXP beginIndSEXP, SEXP endIndSEXP, SEXP betaSEXP, SEXP scoreSEXP, SEXP id1SEXP, SEXP id2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type beginInd(beginIndSEXP);
    Rcpp::traits::input_parameter< int >::type endInd(endIndSEXP);
    Rcpp::traits::input_parameter< mat >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< mat >::type score(scoreSEXP);
    Rcpp::traits::input_parameter< vector<int> >::type id1(id1SEXP);
    Rcpp::traits::input_parameter< vector<int> >::type id2(id2SEXP);
    rcpp_result_gen = Rcpp::wrap(calcRel(beginInd, endInd, beta, score, id1, id2));
    return rcpp_result_gen;
END_RCPP
}
// calculateDivergence
vector<int> calculateDivergence(vector<int> idkin0, double cutoff);
RcppExport SEXP _FastSparseGRM_calculateDivergence(SEXP idkin0SEXP, SEXP cutoffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< vector<int> >::type idkin0(idkin0SEXP);
    Rcpp::traits::input_parameter< double >::type cutoff(cutoffSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateDivergence(idkin0, cutoff));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FastSparseGRM_readfile", (DL_FUNC) &_FastSparseGRM_readfile, 4},
    {"_FastSparseGRM_setmeans", (DL_FUNC) &_FastSparseGRM_setmeans, 2},
    {"_FastSparseGRM_deletedata", (DL_FUNC) &_FastSparseGRM_deletedata, 0},
    {"_FastSparseGRM_deletetranspose", (DL_FUNC) &_FastSparseGRM_deletetranspose, 0},
    {"_FastSparseGRM_postmultiply", (DL_FUNC) &_FastSparseGRM_postmultiply, 2},
    {"_FastSparseGRM_premultiply", (DL_FUNC) &_FastSparseGRM_premultiply, 2},
    {"_FastSparseGRM_calcRel", (DL_FUNC) &_FastSparseGRM_calcRel, 6},
    {"_FastSparseGRM_calculateDivergence", (DL_FUNC) &_FastSparseGRM_calculateDivergence, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_FastSparseGRM(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
