# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readfile <- function(fname, nsamp, RandomLags, num_threads) {
    invisible(.Call(`_FastSparseGRM_readfile`, fname, nsamp, RandomLags, num_threads))
}

setmeans <- function(idmean, noscale = 0L) {
    invisible(.Call(`_FastSparseGRM_setmeans`, idmean, noscale))
}

deletedata <- function() {
    invisible(.Call(`_FastSparseGRM_deletedata`))
}

deletetranspose <- function() {
    invisible(.Call(`_FastSparseGRM_deletetranspose`))
}

postmultiply <- function(u, idmult) {
    .Call(`_FastSparseGRM_postmultiply`, u, idmult)
}

premultiply <- function(u, idmult) {
    .Call(`_FastSparseGRM_premultiply`, u, idmult)
}

calcRel <- function(beginInd, endInd, beta, score, id1, id2) {
    .Call(`_FastSparseGRM_calcRel`, beginInd, endInd, beta, score, id1, id2)
}

calculateDivergence <- function(idkin0, cutoff = -0.025) {
    .Call(`_FastSparseGRM_calculateDivergence`, idkin0, cutoff)
}

